### ISSUE TITLE
Rtf with Revision Tags doesnt get converted to html

### ISSUE THREAD

**Issue by jms47** [mkoertgen/Rtf2Html#1]
[rtf.txt](https://github.com/mkoertgen/Rtf2Html/files/1263230/rtf.txt)

Attached file contain revision tag which doesn't get converted into html.

Save attach file as .rtf and check out put of rtf to html, both are  different.

**Comment by mkoertgen** [comment]
I will have a look and check back to you

**Comment by mkoertgen** [comment]
I am afraid that revision tags / strike through from [Rtf Spec](http://www.biblioscape.com/rtf15_spec.htm#Heading23) are not supported by Microsoft's wpf text editor which is used under the hood.

I tried yours and a similar but more simple example from [MSDN Q/A: Converting between RTF and HTML](https://code.msdn.microsoft.com/Converting-between-RTF-and-aaa02a6e/view/Discussions/3).

[revision_tags_2.txt](https://github.com/mkoertgen/Rtf2Html/files/1269598/revision_tags_2.txt)

The converter works by converting to rtf to xaml (using wpf internals), then to html (manual). Here is what the intermediate Xaml looks like:

```xml
<Section xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xml:space="preserve">
  <Paragraph Margin="0.00,0.00,0.00,0.00" FontFamily="Arial" FontSize="10pt">
    <Span xml:lang="en-US">This is my Second line of text.</Span>
  </Paragraph>
</Section>
```

As i assumed after reading the Q/A above, the resulting Xaml does not contain [TextDecorations](https://msdn.microsoft.com/en-us/library/system.windows.textdecorations%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) like StrikeThrough.

**Comment by jms47** [comment]
I found the solution.
The previous version of RTF was using delete tag which was not recognized by WPF internals.
So replaced delete tag with strike and revised tag with strike0.

**Comment by mkoertgen** [comment]
Great! Would you add test data? 

Closing the issue then.
